### PR TITLE
Create hi

### PR DESCRIPTION
**Pull request by ujwal-vc**
i dont know where to start

### CODE REVIEW

**Comment by RiverNewbury** [comment]
Hi, could you elaborate the problem? What is it that you're trying to do that you don't know where to start on?

**Comment by ujwal-vc** [comment]
I am a beginner in the cryptography I found the elliptical curve
cryptography interesting so I just wanted to do a project in that and I
given the name and this topic to the college as my project but now I am
finding it difficult to understand the topic will I be able to learn it in
a month or two?
Or should I change the project I don't know what to do

**Comment by RiverNewbury** [comment]
You can totally get the hang of this in a month or 2: 
 - First don't stress if you don't get it at first - it is a bit of a hard topic to wrap you head around sometimes
 - If you don't already know the basics do look up about Diffie Hellman and stuff like that
   - https://www.youtube.com/watch?v=NmM9HA2MQGI and https://www.youtube.com/watch?v=Yjrfm_oRO0w are good places to start
 - Then after you've got that (which IDK maybe you already have) 
   - https://www.youtube.com/watch?v=NF1pwjL9-DE to get the basics of it
   - https://www.youtube.com/watch?v=dCvB-mhkT0w another good one of the basics
   - https://www.youtube.com/watch?v=vnpZXJL6QCQ an indepth on the maths and basis of it

After you've looked at all of those I'd just advise giving wikipedia and giving it a thorough read and then just trying to implement them in code yourself. Just start out the standard Edwards without dealing with moding it by anything (although this won't work as floating point errors become super big super quick) then get your head around modulation and modular inverses (https://en.wikipedia.org/wiki/Modular_multiplicative_inverse#Computation) EEA is a good way of calculating then. Then after that you can look at the other types and other ways of calculating as I descirbed the readme. 

I hope this helps <3

**Comment by ujwal-vc** [comment]
Thanks bro this is great

**Comment by RiverNewbury** [comment]
Epic, 
Feel free to pop me message if you have any more questions

**Comment by ujwal-vc** [comment]
Yh sure

**Pull request closed without merging**
